leetcode Q21 and customLinkedList
adiliso/java-course-turing pull request #3
Opened 2024-10-03 17:42 UTC by adiliso

2024-10-03 20:54 UTC, sabuhihuseynov commented on src/main/java/az/edu/turing/homeworks/customlinkedlist/MyLinkedList.java
> +    public MyLinkedList() {
Your initialization is not efficient. You initialize head as an empty node (without value), which complicates operations unnecessarily. instead you could write like head = null, tail = null

2024-10-03 20:56 UTC, sabuhihuseynov commented on src/main/java/az/edu/turing/homeworks/customlinkedlist/MyLinkedList.java
> +        head.val = data;
You're overwriting head.val with the new value and then creating a new ListNode This approach can lead to overwriting or losing the head node. Instead of modifying the current head node's value, create a new node with data and adjust the head pointer

2024-10-03 20:59 UTC, sabuhihuseynov commented on src/main/java/az/edu/turing/homeworks/customlinkedlist/MyLinkedList.java
> +    }
It overwrites the new head's value with null, which is unnecessary. It removes the wrong element. You should return the value of the original head node before updating head to the next node.

2024-10-03 21:01 UTC, sabuhihuseynov commented on src/main/java/az/edu/turing/homeworks/customlinkedlist/MyLinkedList.java
> +    }
The current implementation does not handle the case where the list only has one node. When size == 1, traversing from head to tail is unnecessary and can lead to incorrect results.

2024-10-03 21:02 UTC, sabuhihuseynov commented on src/main/java/az/edu/turing/homeworks/customlinkedlist/MyLinkedList.java
> +    }
The method works but traverses the list unnecessarily to find the index. If you want to insert at index 0, it can call addFirst(), and if you want to insert at the end, it can call add() directly.

2024-10-03 21:04 UTC, sabuhihuseynov commented on src/main/java/az/edu/turing/homeworks/customlinkedlist/MyLinkedList.java
> +        for (int i = 0; i <= index; i++) {
You should loop i < index;

2024-10-03 21:05 UTC, sabuhihuseynov commented on src/main/java/az/edu/turing/homeworks/customlinkedlist/MyLinkedList.java
> +    public boolean remove(Object o) {
why it takes type object not reference type T?

2024-10-03 21:06 UTC, sabuhihuseynov commented on src/main/java/az/edu/turing/homeworks/customlinkedlist/MyLinkedList.java
> +        ListNode<T> curr = head;
null check should be head, and the object parameter

2024-10-03 21:07 UTC, sabuhihuseynov commented on src/main/java/az/edu/turing/homeworks/customlinkedlist/MyLinkedList.java
> +    public void removeAll() {
```
public void removeAll() {
    head = null;
    tail = null;
    size = 0;
}
```

2024-10-03 21:08 UTC, sabuhihuseynov commented on src/main/java/az/edu/turing/homeworks/customlinkedlist/MyLinkedList.java
> +        ListNode<T> curr = head.next;
you skip the head node, and starting second node which is missing the first element in the list.

2024-10-03 21:09 UTC, sabuhihuseynov commented on src/main/java/az/edu/turing/leetcode/Q21/Solution.java
> +                cur.next = new ListNode(list1.val);
use existing list1 node instead of creating new ListNode

2024-10-03 21:09 UTC, sabuhihuseynov commented on src/main/java/az/edu/turing/leetcode/Q21/Solution.java
> +                cur.next = new ListNode(list2.val);
use existing list2 node instead of creating new ListNode

2024-10-03 21:11 UTC, sabuhihuseynov requested changes
pls look

2024-10-06 12:10 UTC, adiliso commented on src/main/java/az/edu/turing/homeworks/customlinkedlist/MyLinkedList.java
> +    public boolean remove(Object o) {
Because java does it like this in its LinkedList implementation.

2024-10-30 07:05 UTC, merged